source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def need_pods
    pod 'Moya', '~> 14.0'
    pod 'Moya/RxSwift', '~> 14.0'

    pod 'SwiftyJSON', '~> 4.0'
end

target 'ProjectTemplate' do
#    need_pods
end

target 'Common' do
  pod 'CocoaLumberjack/Swift'
end

target 'NetworkService' do
    need_pods
end

target 'Business' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'SwiftTheme'
    pod 'SDWebImage', '4.4.7'
    pod 'Keyboard+LayoutGuide','1.3.0'
    pod 'Material'
    pod 'QMUIKit'
end

post_install do |installer|       
   installer.pods_project.targets.each do |target| 
     puts target.name 
   end
end
